import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-roboto" });

export const metadata = {
	title: "Contact +",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`h-screen ${inter.variable} font-sans bg-gray-100 dark:bg-gray-900`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
