import Head from "next/head";
import Image from "next/image";
import { LoginForm } from "@/components/LoginForm";

export default function Home() {
	return (
		<>
			<Head>
				<title>ConnectPlus</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="w-full h-full flex items-center justify-start">
				<div className="hidden md:flex md:w-full h-full flex-col items-center justify-center">
					<div className="max-w-lg">
						<Image
							src={"/images/logo.png"}
							width={1000}
							height={1000}
							alt=""
							className="max-w-lg"
						/>
						<h3 className="text-xl font-semibold text-gray-100">
							"Streamline your contacts and never miss a beat with Connect Plus."
						</h3>
					</div>
				</div>
				<div className="w-full h-full py-8 pl-4 md:w-2/3 max-w-xl flex flex-col justify-start md:justify-center items-center overflow-auto">
					<LoginForm />
				</div>
			</div>
		</>
	);
}
